name: Build and Publish Docker Image

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      GH_PACKAGES_USER: darksos34
      GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
          server-id: github
          server-username: GH_PACKAGES_USER
          server-password: GH_PACKAGES_TOKEN


      - name: Build application
        run: mvn -B clean package -DskipTests

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/darksos34/backend-api:latest